import express from 'express';
import { createAuthRouter } from './authRoutes.js';
import { createParentRouter } from './parentRoutes.js';
import { createStudentRouter } from './studentRoutes.js';
import { createAttendanceRouter } from './attendanceRoutes.js';
import { createResultsRouter } from './resultsRoutes.js';
import { createFeeRouter } from './feeRoutes.js';
import { createDisciplineRouter } from './disciplineRoutes.js';
import { createTicketRouter } from './ticketRoutes.js';
import { createConfigurationRouter } from './configurationRoutes.js';
import { createAnalyticsRouter } from './analyticsRoutes.js';
import { createNotificationRouter } from './notificationRoutes.js';
import { createDashboardRouter } from '../../dashboardRoutes.js';
import { createParentManagementRouter } from '../../parentManagementRoutes.js';
import { createStudentManagementRouter } from '../../studentManagementRoutes.js';
import { createTicketManagementRouter } from '../../ticketManagementRoutes.js';
import { createUserManagementRouter, createRoleManagementRouter } from '../../userRoleManagementRoutes.js';
import { createAuditManagementRouter } from '../../auditManagementRoutes.js';
import { createOTPManagementRouter } from '../../otpManagementRoutes.js';
import { createConversationManagementRouter } from '../../conversationManagementRoutes.js';
import { createBroadcastManagementRouter } from '../../broadcastManagementRoutes.js';
import { createConnectorManagementRouter } from '../../connectorManagementRoutes.js';
import { createSettingsManagementRouter } from '../../settingsManagementRoutes.js';
import { createCalendarManagementRouter } from '../../calendarManagementRoutes.js';
import { createProfileManagementRouter } from '../../profileManagementRoutes.js';
import { createSystemAdminRouter } from '../../system-admin/index.js';

export const createApiV1Router = (dependencies = {}) => {
  const router = express.Router();

  router.use('/dashboard', createDashboardRouter(dependencies));
  router.use('/admin/parents', createParentManagementRouter(dependencies));
  router.use('/admin/students', createStudentManagementRouter(dependencies));
  router.use('/admin/tickets', createTicketManagementRouter(dependencies));
  router.use('/admin/users', createUserManagementRouter(dependencies));
  router.use('/admin/roles', createRoleManagementRouter(dependencies));
  router.use('/admin/audit', createAuditManagementRouter(dependencies));
  router.use('/admin/otp', createOTPManagementRouter(dependencies));
  router.use('/admin/conversations', createConversationManagementRouter(dependencies));
  router.use('/admin/broadcasts', createBroadcastManagementRouter(dependencies));
  router.use('/admin/connectors', createConnectorManagementRouter(dependencies));
  router.use('/admin/settings', createSettingsManagementRouter(dependencies));
  router.use('/admin/calendar', createCalendarManagementRouter(dependencies));
  router.use('/profile', createProfileManagementRouter(dependencies));
  router.use('/system-admin', createSystemAdminRouter(dependencies));
  
  router.use('/auth', createAuthRouter(dependencies));
  router.use('/parents', createParentRouter(dependencies));
  router.use('/students', createStudentRouter(dependencies));
  router.use('/attendance', createAttendanceRouter(dependencies));
  router.use('/results', createResultsRouter(dependencies));
  router.use('/fees', createFeeRouter(dependencies));
  router.use('/discipline', createDisciplineRouter(dependencies));
  router.use('/tickets', createTicketRouter(dependencies));
  router.use('/configuration', createConfigurationRouter(dependencies));
  router.use('/analytics', createAnalyticsRouter(dependencies));
  router.use('/notifications', createNotificationRouter(dependencies));

  return router;
};
