import express from 'express';
import { createAuthRouter } from './authRoutes.js';
import { createParentRouter } from './parentRoutes.js';
import { createStudentRouter } from './studentRoutes.js';
import { createAttendanceRouter } from './attendanceRoutes.js';
import { createResultsRouter } from './resultsRoutes.js';
import { createFeeRouter } from './feeRoutes.js';
import { createDisciplineRouter } from './disciplineRoutes.js';
import { createTicketRouter } from './ticketRoutes.js';
import { createConfigurationRouter } from './configurationRoutes.js';
import { createAnalyticsRouter } from './analyticsRoutes.js';
import { createNotificationRouter } from './notificationRoutes.js';
import { createDashboardRouter } from '../../../routes/dashboardRoutes.js';
import { createParentManagementRouter } from '../../../routes/parentManagementRoutes.js';
import { createStudentManagementRouter } from '../../../routes/studentManagementRoutes.js';
import { createTicketManagementRouter } from '../../../routes/ticketManagementRoutes.js';
import { createUserManagementRouter, createRoleManagementRouter } from '../../../routes/userRoleManagementRoutes.js';
import { createAuditManagementRouter } from '../../../routes/auditManagementRoutes.js';
import { createOTPManagementRouter } from '../../../routes/otpManagementRoutes.js';
import { createConversationManagementRouter } from '../../../routes/conversationManagementRoutes.js';
import { createBroadcastManagementRouter } from '../../../routes/broadcastManagementRoutes.js';
import { createConnectorManagementRouter } from '../../../routes/connectorManagementRoutes.js';
import { createSettingsManagementRouter } from '../../../routes/settingsManagementRoutes.js';
import { createCalendarManagementRouter } from '../../../routes/calendarManagementRoutes.js';
import { createProfileManagementRouter } from '../../../routes/profileManagementRoutes.js';
import { createSystemAdminRouter } from '../../../routes/system-admin/index.js';
import { createSystemAdminApiRouter } from '../../../routes/api/v1/systemAdminRoutes.js';

export const createApiV1Router = (dependencies = {}) => {
  const router = express.Router();

  router.use('/dashboard', createDashboardRouter(dependencies));
  router.use('/admin/parents', createParentManagementRouter(dependencies));
  router.use('/admin/students', createStudentManagementRouter(dependencies));
  router.use('/admin/tickets', createTicketManagementRouter(dependencies));
  router.use('/admin/users', createUserManagementRouter(dependencies));
  router.use('/admin/roles', createRoleManagementRouter(dependencies));
  router.use('/admin/audit', createAuditManagementRouter(dependencies));
  router.use('/admin/otp', createOTPManagementRouter(dependencies));
  router.use('/admin/conversations', createConversationManagementRouter(dependencies));
  router.use('/admin/broadcasts', createBroadcastManagementRouter(dependencies));
  router.use('/admin/connectors', createConnectorManagementRouter(dependencies));
  router.use('/admin/settings', createSettingsManagementRouter(dependencies));
  router.use('/admin/calendar', createCalendarManagementRouter(dependencies));
  router.use('/profile', createProfileManagementRouter(dependencies));
  router.use('/system-admin', createSystemAdminRouter(dependencies));
  router.use('/system', createSystemAdminApiRouter(dependencies));
  
  router.use('/auth', createAuthRouter(dependencies));
  router.use('/parents', createParentRouter(dependencies));
  router.use('/students', createStudentRouter(dependencies));
  router.use('/attendance', createAttendanceRouter(dependencies));
  router.use('/results', createResultsRouter(dependencies));
  router.use('/fees', createFeeRouter(dependencies));
  router.use('/discipline', createDisciplineRouter(dependencies));
  router.use('/tickets', createTicketRouter(dependencies));
  router.use('/configuration', createConfigurationRouter(dependencies));
  router.use('/analytics', createAnalyticsRouter(dependencies));
  router.use('/notifications', createNotificationRouter(dependencies));

  return router;
};
